swagger: "2.0"
info: 
  description: "A simple timecard application"
  version: "0.0.1"
  title: "Reed's Timecard Application"
basePath: "/"
paths:
  /employee: 
    post:
      tags:
       - "employee"
      summary: "Allows you to create a new employee"
      description: ""
      operationId: "createEmployee"
      consumes:
      - "application/json"
      produces:
      - "application/json"  
      parameters:
      - in: "body"
        name: "body"
        description: "Create an employee using a name and the date of birth (DOB). This will return the employee's unique ID"
        schema:      # Request body contents
          $ref: '#/definitions/CreateEmployee'
      responses:
        202:
          description: "The json payload has been acepted, attempting creation of Employee ID."
          schema:
            $ref: "#/definitions/EmployeePostResponse"
        400:
          description: "Error in the POST payload resulted in a bad request."
          schema: 
            $ref: "#/definitions/Error"
  /employee/ClockIn:
    post:
      tags:
        - "timecard"
      summary: "Allows you to clock in"
      description: ""
      operationId: "getClockIn"
      consumes: 
      - "application/json" 
      produces:
      - "application/json" 
      parameters:
      - in: "body"
        name: "EmployeeId"
        description: "Clock in as an employee"
        schema:
          $ref: "#/definitions/ClockIn"
      responses:
        200:
          description: "The clock in time has been created"
          schema:
            $ref: "#/definitions/ClockInResponse"
        400: 
          description: "Error for the clock in"
          schema: 
            $ref: "#/definitions/Error"
definitions:
  CreateEmployee:
      type: object
      properties:
        Name:
          type: string
          example: John Smith
        DoB:
          type: string
          example: "9/5/1994"
      required:
        - Name
        - DoB
  ClockIn:
      type: object
      properties:
        ID:
          type: integer
          # x-go-name: Id
          example: "1" 
      required:
        - ID
  EmployeePostResponse:
    type: object
    properties:
      name: 
        type: "string"
        description: "Name of the Employee"
        example: "John Smith"
      employeeID:
        type: "string"
        description: "Unique Id for the created employee"
        example: "1"
  ClockInResponse:
    type: object
    properties:
      name:
        type: "string"
        description: "Name of the Employee"
        example: "John Smith"
      employeeID:
        type: "string"
        description: "Unique ID for that employee"
        example: "1"
      clockIn:
        type: "string"
        description: "Clock In time for the employee"
  Error: 
    type: object
    properties:
      code:
        type: string
        description: "Code identification of the problem."
      messages:
        type: array
        items:
          type: string
          example: "Something failed."
        description: "Clear, complete description of the problem"