// Code generated by MockGen. DO NOT EDIT.
// Source: timeCardSimple/app/domain/timecard (interfaces: Service)

// Package timecardtest is a generated GoMock package.
package timecardtest

import (
	context "context"
	reflect "reflect"
	time "time"
	id "timeCardSimple/app/domain/id"
	timecard "timeCardSimple/app/domain/timecard"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ClockIn mocks base method.
func (m *MockService) ClockIn(arg0 context.Context, arg1 id.ID, arg2 time.Time) (*timecard.Timecard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClockIn", arg0, arg1, arg2)
	ret0, _ := ret[0].(*timecard.Timecard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClockIn indicates an expected call of ClockIn.
func (mr *MockServiceMockRecorder) ClockIn(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClockIn", reflect.TypeOf((*MockService)(nil).ClockIn), arg0, arg1, arg2)
}
