// Code generated by MockGen. DO NOT EDIT.
// Source: timeCardSimple/app/domain/timecard (interfaces: Service)

// Package timecardtest is a generated GoMock package.
package timecardtest

import (
	context "context"
	reflect "reflect"
	id "timeCardSimple/app/domain/id"
	timecard "timeCardSimple/app/domain/timecard"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateTimecard mocks base method.
func (m *MockService) CreateTimecard(arg0 context.Context, arg1 id.ID) (*timecard.Timecard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTimecard", arg0, arg1)
	ret0, _ := ret[0].(*timecard.Timecard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTimecard indicates an expected call of CreateTimecard.
func (mr *MockServiceMockRecorder) CreateTimecard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTimecard", reflect.TypeOf((*MockService)(nil).CreateTimecard), arg0, arg1)
}
