// Code generated by MockGen. DO NOT EDIT.
// Source: timeCardSimple/app/domain/timecard (interfaces: Repo)

// Package timecardtest is a generated GoMock package.
package timecardtest

import (
	context "context"
	reflect "reflect"
	timecard "timeCardSimple/app/domain/timecard"

	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// CreateEmployeeTimecard mocks base method.
func (m *MockRepo) CreateEmployeeTimecard(arg0 context.Context, arg1 *timecard.Timecard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployeeTimecard", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEmployeeTimecard indicates an expected call of CreateEmployeeTimecard.
func (mr *MockRepoMockRecorder) CreateEmployeeTimecard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployeeTimecard", reflect.TypeOf((*MockRepo)(nil).CreateEmployeeTimecard), arg0, arg1)
}
