// Code generated by MockGen. DO NOT EDIT.
// Source: timeCardSimple/app/domain/weeklysummary (interfaces: Repo)

// Package weeklysummarytest is a generated GoMock package.
package weeklysummarytest

import (
	context "context"
	reflect "reflect"
	id "timeCardSimple/app/domain/id"
	weeklysummary "timeCardSimple/app/domain/weeklysummary"

	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// CreateWeeklySummary mocks base method.
func (m *MockRepo) CreateWeeklySummary(arg0 context.Context, arg1 *weeklysummary.WeeklySummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWeeklySummary", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWeeklySummary indicates an expected call of CreateWeeklySummary.
func (mr *MockRepoMockRecorder) CreateWeeklySummary(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWeeklySummary", reflect.TypeOf((*MockRepo)(nil).CreateWeeklySummary), arg0, arg1)
}

// GetWeeklySummaryByEmployeeID mocks base method.
func (m *MockRepo) GetWeeklySummaryByEmployeeID(arg0 context.Context, arg1 id.ID) (*weeklysummary.WeeklySummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeeklySummaryByEmployeeID", arg0, arg1)
	ret0, _ := ret[0].(*weeklysummary.WeeklySummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeeklySummaryByEmployeeID indicates an expected call of GetWeeklySummaryByEmployeeID.
func (mr *MockRepoMockRecorder) GetWeeklySummaryByEmployeeID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeeklySummaryByEmployeeID", reflect.TypeOf((*MockRepo)(nil).GetWeeklySummaryByEmployeeID), arg0, arg1)
}
