// Code generated by MockGen. DO NOT EDIT.
// Source: timeCardSimple/app/domain/payperiod (interfaces: Repo)

// Package payperiodtest is a generated GoMock package.
package payperiodtest

import (
	context "context"
	reflect "reflect"
	id "timeCardSimple/app/domain/id"
	payperiod "timeCardSimple/app/domain/payperiod"

	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// CreatePayPeriod mocks base method.
func (m *MockRepo) CreatePayPeriod(arg0 context.Context, arg1 *payperiod.PayPeriod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayPeriod", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePayPeriod indicates an expected call of CreatePayPeriod.
func (mr *MockRepoMockRecorder) CreatePayPeriod(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayPeriod", reflect.TypeOf((*MockRepo)(nil).CreatePayPeriod), arg0, arg1)
}

// GetPayPeriodByEmployeeID mocks base method.
func (m *MockRepo) GetPayPeriodByEmployeeID(arg0 context.Context, arg1 id.ID) (*payperiod.PayPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayPeriodByEmployeeID", arg0, arg1)
	ret0, _ := ret[0].(*payperiod.PayPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayPeriodByEmployeeID indicates an expected call of GetPayPeriodByEmployeeID.
func (mr *MockRepoMockRecorder) GetPayPeriodByEmployeeID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayPeriodByEmployeeID", reflect.TypeOf((*MockRepo)(nil).GetPayPeriodByEmployeeID), arg0, arg1)
}
